# Site settings
title: Dave's Bird Blog
email: dave@bighairydave.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bighairydave
github_username:  bighairydave

defaults:
  -
    scope: 
      path: ""
    values:
      author: "Dave"
      layout: "post"
      email: "dave@bighairydave.com"
      copyright: "© David Tyler 2015"
      category: "news"

# Build settings
markdown: kramdown



