# Site settings
title: Adventures in Bird Watching
tagline: "Wherein 'adventure' means 'making lists'."
email: dave@bighairydave.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about birds, but more importantly a blog about blogging about birds. Yeah.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bighairydave
github_username:  bighairydave

defaults:
  -
    scope: 
      path: ""
    values:
      author: "Dave"
      layout: "post"
      email: "dave@bighairydave.com"
      copyright: "© David Tyler 2015"
      category: "news"

# Build settings
markdown: kramdown



